let words1 = [
	['school', 'blackboard'],
	['tower', 'bell'],
	['sea', 'tide'],
	['family', 'marriage'],
	['newspaper', 'interview'],
	['sonata', 'joy'],
	['banner', 'camp'],
	['tendency', 'increment'],
	['mother', 'child'],
	['insect', 'caterpillar'],
	['river', 'ship'],
	['coast', 'beach'],
	['gun', 'bullet'],
	['blacksmith', 'metal'],
	['home', 'room'],
	['building', 'hall'],
	['rain', 'flood'],
	['avenue', 'tree'],
	['decency', 'truth'],
	['decree', 'decision'],
	['diamond', 'hardness'],
	['result', 'effect'],
	['occupation', 'doctor'],
	['book', 'story'],
	['attack', 'operation'],
	['cat', 'soul'],
	['doll', 'cradle'],
	['episode', 'happiness'],
	['railroad', 'steam'],
	['kitchen', 'pot'],
	['countryside', 'swamp'],
	['musician', 'pianist'],
	['industry', 'factory'],
	['clothing', 'scarf'],
	['car', 'headlight'],
	['prison', 'gangster'],
	['gale', 'wind'],
	['bouquet', 'blossom'],
	['bottle', 'toast'],
	['group', 'person'],
	['crisis', 'emergency'],
	['girl', 'engagement'],
	['harbor', 'crane'],
	['garden', 'flowerbed']
];

let words2 = [
	['rider', 'switch'],
	['fire', 'smoke'],
	['animal', 'fox'],
	['road', 'car'],
	['weaver', 'troubles'],
	['flakes', 'rescue'],
	['rein', 'turn'],
	['mission', 'messenger'],
	['furniture', 'chair'],
	['body', 'blood'],
	['army', 'admiral'],
	['friend', 'loyalty'],
	['bird', 'lark'],
	['celebration', 'alcohol'],
	['reptile', 'frog'],
	['grain', 'oats'],
	['joint', 'knuckle'],
	['artist', 'painting'],
	['statement', 'doubt'],
	['revolt', 'policeman'],
	['alliance', 'betrayal'],
	['event', 'incident'],
	['factory', 'foreman'],
	['plant', 'leaf'],
	['tenant', 'rent'],
	['commercial', 'candy'],
	['giant', 'club'],
	['trip', 'map'],
	['mountain', 'boulder'],
	['ruler', 'palace'],
	['play', 'drama'],
	['illness', 'doctor'],
	['church', 'heaven'],
	['infection', 'bacteria'],
	['university', 'semester'],
	['underworld', 'crime'],
	['instrument', 'bagpipes'],
	['glacier', 'avalanche'],
	['idea', 'proverb'],
	['faith', 'renouncement'],
	['theory', 'concept'],
	['authority', 'state'],
	['fir', 'needle'],
	['circus', 'clown']
];

const pictures = [
	'IMG_0001.jpeg',
	'IMG_0018.jpeg',
	'IMG_0086.jpeg',
	'IMG_0091.jpeg',
	'IMG_0093.jpeg',
	'IMG_0190.jpeg',
	'IMG_0227.jpeg',
	'IMG_0235.jpeg',
	'IMG_0395.jpeg',
	'IMG_0408.jpeg',
	'IMG_0410.jpeg',
	'IMG_0508.jpeg',
	'IMG_0516.jpeg',
	'IMG_0549.jpeg',
	'IMG_0558.jpeg',
	'IMG_0567.jpeg',
	'IMG_0570.jpeg',
	'IMG_0577.jpeg',
	'IMG_0587.jpeg'
];

export { words1, words2, pictures };
